@startmindmap
*[#Orange] Negotations (science, not art)
left side
** Prepararation
*** Asses BATNA
**** Yours
**** Theirs (Remember photograph!)
*** Calculate reservation value
**** Yours
**** Theirs
*** Find Zopa

** Their initial offer
*** Ingore the anchor (turn their focus elsewhwere)
*** Separate information from influence (try to update ZOPA)
*** Avoid dwelling on the anchor
*** Make anchored counteroffer, propose moderation\n(if can't dismiss their anchor)
*** Give them time to moderate the offer withour losing FrameFontColor

** Your offer first
*** Keep the entire ZOPA in play
*** Provide justification for your offer\n(if they challange your assumptions - good. Time is spend on your anchor)
*** Set High but realistic aspirations and consider relationship

** Acquiring information
*** Exhaust all pre-negotiation sources of information
*** Identify your assumptions prior to Negotation
*** Ask question to challange your assumptions
*** Ask indirect questions
*** Protect yourself from lies using contingency contracts

right side
** Haggling
*** Focus on their BATNA and reservation value
*** Avoid makng unilateral concessions
*** Be comfortable with silence\n(When you speak when it is their turn, you will be paying)
*** Label your concessions
*** Define what it means to reciprocate
*** Make contingent concessions
*** Be aware of effects of diminishing rates of concessions

** Their first offer that you love 
*** Take time to ponder the offer
*** Take more their money\n(they feel better with small negoations)
*** Give something back to strengthen the relationship
*** Don't celebrate - think! Why someone is so generous? Are you to cheap?

** Creating value (70% from 100$ or 70% of 200$?)
*** Negotiate multiple issues
**** Do logrolling (negotiate across multiple issues)
**** More issues = more currency
**** Find best package deal (make package offers)
**** Find their priorities and share yours (carefully) to create max value.
***** Delivery date
***** Financing
***** Qualiity
***** Contract length
***** last-look provisions
***** Exclusivity
***** Level of service support
***** Warranties
***** Future business
*** Pareto improvement
**** If you leave the table not knowing very much about\ntheir priorites and interests, you have missed something!
**** Contingency can create value (67) when can be measured objectively.
*** The goal is not to overhelm but give different ways to compensate you.
*** Create scoring system
*** Calculate package reservation value
*** Identify other party multiple interests
*** Pretend that everything is very\nimportant! (don't give for free)
*** Leverage differences of all types to create value (risk & insurances!)
*** Post-settlement settlement (PSS)! 79
*** Investigative negoations
**** Don't just ask what, ask **Why**
**** Seek to reconcile interests, not demands (votes in USA)
**** Create common ground with uncommon allies
**** Interpret demands as opportunites
**** Don't dismiss anything as their problem (shipping ex 92)
**** Don't let negoation end with simple rejection.
**** Build trust and share information
**** Ask when you are surprised or sceptical
**** Give away some information (just some)
**** Make 2 offers that are of equal\nvalue to you but differ slightly.
***** Uncovers priorities
***** Anchor more strongly


legend
"Man hopes, Genius creates." - Ralph Waldoo Emerson
BATNA - Best alternative to negotiaded agreement
ZOPA - Zone of possible agreement
"Negotation geniuses know how to act on information they have, acquire information they don't have, and protect themselves from information they cannot obtain."
Anchor - offer that focuses the other negatiator's attention and expectations
"A good negotiator will do whatever it takes to close the deal, while a negotation genius will do whatever it takes to maximize value in the deal."
endlegend
@endmindmap

