@startmindmap
*[#Orange] Negotations (science, not art)
left side
** Prepararation
*** Asses BATNA
**** Yours
**** Theirs (Remember photograph!)
*** Calculate reservation value
**** Yours
**** Theirs
*** Find Zopa

** Their initial offer
*** Ingore the anchor (turn their focus elsewhwere)
*** Separate information from influence (try to update ZOPA)
*** Avoid dwelling on the anchor
*** Make anchored counteroffer, propose moderation\n(if can't dismiss their anchor)
*** Give them time to moderate the offer withour losing FrameFontColor

** Your offer first
*** Keep the entire ZOPA in play
*** Provide justification for your offer\n(if they challange your assumptions - good. Time is spend on your anchor)
*** Set High but realistic aspirations and consider relationship

** Acquiring information
*** Exhaust all pre-negotiation sources of information
*** Identify your assumptions prior to Negotation
*** Ask question to challange your assumptions
*** Ask indirect questions
*** Protect yourself from lies using contingency contracts

right side
** Haggling
*** Focus on their BATNA and reservation value
*** Avoid makng unilateral concessions
*** Be comfortable with silence\n(When you speak when it is their turn, you will be paying)
*** Label your concessions
*** Define what it means to reciprocate
*** Make contingent concessions
*** Be aware of effects of diminishing rates of concessions

** Their first offer that you love 
*** Take time to ponder the offer
*** Take more their money\n(they feel better with small negoations)
*** Give something back to strengthen the relationship
*** Don't celebrate - think! Why someone is so generous? Are you to cheap?



legend
"Man hopes, Genius creates." - Ralph Waldoo Emerson
BATNA - Best alternative to negotiaded agreement
ZOPA - Zone of possible agreement
"Negotation geniuses know how to act on information they have, acquire information they don't have, and protect themselves from information they cannot obtain."
Anchor - offer that focuses the other negatiator's attention and expectations
endlegend
@endmindmap

