@startmindmap
*[#Orange] Negotations (science, not art)
left side
** Biases\nand defenses
*** Fixed pie
**** Try to bring multiple issues
*** Vivid points
**** Create scoring system
**** Separate influence from information
*** Non rational commitment
**** Create exit strategy
**** Devil's advocate
**** Anticipate and react before escalation forces
*** Framing and reference points
**** Evaluate different reference points
**** Reframe before risky strategy ie Ultimatum
*** Egocentrism
**** Veil of ignorance
*** General defenses
**** Learn from the pasts\non the biases failures
**** Avoid time pressure
**** Use analogies
**** Outsider lens
*** Help them in biases
**** Give them time
**** Encourage to think about each issue
**** Callibrate info from others
**** Use contingency contracts to resolve conflicts from biases

** Negotatiating from\nposition of weakness
*** Act
**** Don't reveal that you are weak
**** Leverage their weakness
**** Leverage your Distinct Value Proposition (DVP) (The office)
**** Submit multiple proposals
**** Lower your bid just enough to get to 2nd round
**** Take the agent (proxy) out of the game (243)
**** If very week, ask them to help you (247)
**** Strategize on whole negotation portfolio
*** Build strength
**** Build coalitions with other week parties
**** They may need you to survive
**** Understand and attack their source of power



right side
** Influences\nand defenses
*** Highlight their loses, not gains
*** Disaggreage their gains, aggregate their losses
*** Door in face (no first to recompansate)
*** Foot in the door (small yeses till the jackpot)
*** Power of justification (168 - "because")
*** Power of social proof (behaviour of others)
*** Make token unilateral concession (so they recompensate)
*** Use reference points
*** Defenses
**** Scoring system
**** Prepare and anticipate
**** Separate influence from information
**** Rephrase the offer in other terms
**** Devils advocate
**** Avoid time pressure

** Avoiding lies
*** Look prepared
*** Signal ability to obtain info
*** Ask less threatening, indirect questions
*** Don't lie
*** Detect lie
**** Gather info from multiple sources
**** Triangulate on the truth
**** Set a trap
**** Lookout out for responses that dont answer the questions
**** Contingency contracts
*** Dealing with lie
**** Do i want to continue negotation?
**** Was this really a lie?
**** Warn or Confront (211)
*** Smart alternatives to laying
**** Incorporate reputation and relationship
**** Anticipate to answer difficult questions
**** Change the reality (sent CV)
**** Avoid time pressure
**** Refuse to answer
**** Offer anwer to different question
**** Eliminate constraint that temp to lie

** Trheats and Ultimatum
*** Ignore or focus on softening 
*** Neutralize any additional threats (anticipate)
*** If you don't find it credible, let them know
*** Give them face-saving way to not stick to the ultimatum (278)


legend
If the two sides in negotation are able to identify and eliminate the source of distrust, trust can clearly be rebuild.
When both paries have a weak BATNA, it means that the ZOPA is large.
Ethics in negotation is about actively striving to be a better person, not about reaching and settling for an acceptable status quo.
endlegend
@endmindmap

