@startmindmap
*[#Orange] Peopleware
** Good manager
*** Encourage people to make errors by asking about problems \nand making sure that "no probelms" isn't the best answer.
*** [1] Understands that uniquness is what makes the team great
*** Allows people to do the estimates
*** Tries to make peace and quiet workplace
*** [2] Lets the people be themselves, event when they deviate from corporate norm
*** Understands that strong identity of team is also his success
*** Never break into sweat. It looks so easy\nthat no one can believe they are mnaging at all
*** Open Kimono [3]
**** (162 - I don't read contracts)
**** Breaks chaos to small packets and delegates it to others (223)
*** Understands that good team doesn't need managment
*** [4] Helps to achieve convergence of method by training, tools, enouraging peer review
*** [5] Knows that risk managment is about mitigation of the risk if it happens
*** Tries to create learning organisation
*** Some Good practices
**** Power of veto for everyone (Hitachi Software - 23)
**** Data collected on individual's performance\nhas to be used only to benefit that individual.
**** Prefer async communication on things you are not currenty on.
**** Wokrplace is important; work space, meeting space, social space.
**** Audition interview
**** Peer review
**** To introduce change don't demean old ways, celebrate them! (206)
**** Release one person at the start of each meeting\nmaking statement that he is to important to attend the meeting. (apple 191)
**** Create policy of reintroduction of small amounts of disorder
***** Pilot projets (224)
***** War games
***** Brainstorming
***** Procative training experiences
***** Training, trips, conferences, celebrations and retreats
*** Respects free electrons (234)

** Leadership
*** Without positional authority\n(only natural - the master knows how to do the work and the apprentice does not).
**** Step up to the task
**** Be evidently fit for the task
**** Prepare for the task by doing homework AOT
**** Maximize value for everyone
**** Do it with humor and obvious goodwill
**** Charisma helps
*** Rebel leadership is often required to innovate (101 - good chapter)
*** Leadership may originate from everywhere
*** Leadership as service almost always\noperates without official permission (101)
*** If companies were more inclined to let leadership arise naturally,\nthey wouldn't need to produce so much hot air talking about it.

** Some important facts
*** Meeting agenda is important (189)
*** Change is not [old status] -> [new status].\nIt is [old status] -> [chaos] -> [practice and integration] -> [new state]
*** Jelled team - group of people so strongly knit\nthat the whole is greater than the sum of the parts.
*** In the best organisations the short term is not the only thing that matters.\nWhat matters more is being best and that's king-term concept. (Example : retraining)
*** People who perform better tent to gravitate\ntoward orgs that provide better workplace.
*** No estimates seems to cause best productivity (29)
*** People who are desperate enough\ndon't look very hard at evidences
*** Howthorne effect - pople perform better when they're trying something new
**** Make non-standard approaches the rule
**** Don't allow to much new at the same time\n(how would you know what caused positive change?)
*** Gibs Law: Anything you need to quantify can be\nmeasured in some way that is superior to not measuring it at all.
*** People stays at companies that invests and trust in them\n(widespread sense that you are expected to stay).
*** Edwartd deBono "Lateral Thinking" - Inversion technique\n(look how to achieve the oposite - 144)

left side

** Teamicide (team suicide)
*** Defensive managment
**** No trust in your people
**** High level of control
*** Bureaucracy
*** Physical separation 
**** No casual interaction
**** No group spce - no chance\nof group culture forming
*** Clique Control (managers are not part of team - 149)
*** Annual salary reviews
*** Managment by objectives (MBO)
*** Praise certain workers for extraordinary accomplishment (causes competition)
*** Award, prizes, bonuses tied to performance
*** Performance measurement in almost any form

** Team chemistry building strategy
*** Make cult of Quality
**** Good enough is the death knell for a jelling team
**** Only perfect is good enough for us
*** Provide lots of satisfying closure
*** Build sense of elitness
*** Allow and encourage heterogeneity
*** Preserve and protect successful teams
*** Provide strategic but not tactical direction
*** Sense of identity

** Why people leave?
*** Just passing-through mentality
*** A feeling of disposability (interchargable parts)
*** A sense that loyalty would be ludicrous (results from above)
*** Because other people leave
*** Because they are bored (standards, same project too long)

** Bad Manager
*** [1] Fears about "key persons", tries to make everyone the same.
*** Spanish Theory (more without paying - free overhours, etc)
*** [2] Anything that annoys weak manager is almost by definition unprofessional.
*** Law of Parkinson - The only way to get work done\nat all is to set impossibly optimistic devlivery date.
*** [3] Defensive managment (control & verification).\nDefensive managers are on their own in case of fackup.
*** [4] Methodology madness (paperwork, lack of responsibility)
*** [5] Uses risk managment to eliminate risk at all cost
*** Wastes people time (no meeting agenda etc, inviting to much people, to much meetings)

legend
"The manager's function is not to make people work, byt to make it possible for people to work."
"People under pressure don't work better - they just work faster."
"Quality, far beyond that required by the end user, is a means to higher productivity."
"Quality is free, but only for those who are willing to pay heavily for it."
"Purpose of a team is not goal attainment but goal alignment."
"Voluminous documentation is part of the problem, not part of the solution."
endlegend
@endmindmap

