@startmindmap
*[#Orange] RETRAINED
left side
** **Respected** - Creative in removing\nimpediments to productivity.
*** Be humble (to practice ask for help frequently)
*** Ask for feedback for you.
*** Be honest, reliable, have moral code = respect.
*** Make many small commitments (don't overpromise).
*** First - Ask the team (on real and abstract).
*** Make yourself redundant.
*** Survive coorporation
**** SWOT
**** Measure things!
**** Are plans are wrong! (41)
**** It takes 3-4 sprints to gain\npredictable velocity.
**** Team cannot think that they are worthy\nonly if they met the expectations of PO (42).
*** Train the team members to hold each\nother to account for failing honour agreements.
*** Create feedback culture (AID model).
**** Actions
**** Impacts
**** Desired outcome

** **Enabling** - Passionate aboyt helping\nothers to be effective.
*** Battle mapping
*** Bullshit buzzer
*** Bullshit bingo
*** Remove proxies, Ecourage customer collaboration.

** **Tactful** - Diplomacy personified.
*** Note sign of progress (even the small marks!)
*** Practice staying calm (count to 10)
*** Create safe environment (introduce audience gradually)
*** Typical sprint length debate (89)
*** Don't break the silence!


** **Resourceful** - Reputation for integrity\nin team and organisation.
*** Find solutions by imaging what would make\na problem worse, as opposed to better.
*** Team tourisms
*** Make work fun
*** game of Delight (110)
*** **Feedback-questions**
**** How would you like it to be?
**** If you were me what would you do first?
**** If there we absolutely no constraints, what would you do?
**** How could we make this fun or at least bearable?
**** What assumptions do we have that might not be true?
*** Rather than having a list of solutions they are required\nto implement, the team then have free rein to solve\nthe problem and meet business needs within those\nconstraints in the most creative way possible.
*** Keep it fresh
**** Start meeting with a joke
**** Introduce food or drink
**** Icebrakers, fun fact
**** Draw your updated in a Pictionary style
**** Change location of daily scrum
**** Add an extra element to the 3 questions (Sth I appreciate of a member)
*** Retros
**** 1-3 action points from retro (store in backlog or separate)
**** The rule of seven (7 solutions)
**** ORID (talking duck) 
**** Teach people to fish rather than giving fish
**** Continous retros
**** Redefine failure (126)
**** Make data visible (ie lack of focus on quality, gamify)
**** Shisa kanko
**** Retrospective of Retrospective, **Retro hooks!**

right side
** **Alternative** - Prepared to promote\na counter culture.
*** Servant leaders flatten the hierarchies
*** Seek alternative perspectives from different industries
*** T-shaped people (144)
*** Avoid scrummerfall (code sprint, test sprint, fix sprint)
*** From time to time PO may do the demo
*** Sometimes break the rule and experiment!
*** End of sprint questions (165 - ie have velocity changed?)

** **Inspiring** - Generate enthusiasm\nand energy in others.
*** Scrum master as radical change agent
*** Greg Dollars instead "Story points"
*** Sprint goals
**** Bottom up - find group of related PBI
**** Top-down (usually by PO) - desired future state
**** Avoid forced-fit!
**** Use goal metaphors
*** Motiviation 3.0
**** Autonomy
**** Mastery
**** Purpose
*** Burndown is for the DevTeam only!
*** Teams should be encouraged to find alternative\nways of meeting the goal of a part of the framework.

** **Nurturing** - They enjoy helping both\nindividuals and teams to grow.
*** Find "The great team definition"
*** Coach to Strengths to Overcome Weakness
*** I'd rather have a hole in my team than an asshole in my team.
*** Hire, fire team members by team.

** **Empathic** - Sensitive to those around.
*** Develop talent for listening
**** One-word storytelling
**** The three-headed epxert
**** Story spines
**** First letter, last letter
*** Yes, but VERSUS Yes and (217)

** **Disruptive** - Break old status quo\n and help create the new. 
*** Use minimalistic tools
*** Value principel over rules (aka rebel leadership)
*** Note the Tuckman model - Team formation stages
*** Use conflict to grow the team
legend
User storeis are placeholder for conversation. 
The opposite of fun is not work it's depression. We believe work can be fun, and when it is you get more done. Sam Laing & Karen Greaves.
It is far better to be trusted and respected than to be liked. 
Henry Stimson - The only way to make a man trustworthy is to trust him.
All plans are arguably wrong anyway because, as soon as they are made, the information used to make them is immediately out of date.
The leader is then effective when each team member is able to make the right decision. - Anna Markiewicz friend from US army.
endlegend
@endmindmap