@startmindmap
*[#Orange] RETRAINED
left side
** **Respected** - Creative in removing\nimpediments to productivity.
*** Be humble (to practice ask for help frequently)
*** Ask for feedback for you.
*** Be honest, reliable, have moral code = respect.
*** Make many small commitments (don't overpromise).
*** First - Ask the team (on real and abstract).
*** Make yourself redundant.
*** Survive coorporation
**** SWOT
**** Measure things!
**** Are plans are wrong! (41)
**** It takes 3-4 sprints to gain\npredictable velocity.
**** Team cannot think that they are worthy\nonly if they met the expectations of PO (42).
*** Train the team members to hold each\nother to account for failing honour agreements.
*** Create feedback culture (AID model).
**** Actions
**** Impacts
**** Desired outcome

** **Enabling** - Passionate aboyt helping\nothers to be effective.
*** Battle mapping
*** Bullshit buzzer
*** Bullshit bingo
*** Remove proxies, Ecourage customer collaboration.

** **Tactful** - Diplomacy personified.
*** Note sign of progress (even the small marks!)
*** Practice staying calm (count to 10)
*** Create safe environment (introduce audience gradually)
*** Typical sprint length debate (89)
*** **Feedback-questions**
*** Don't break the silence!


** **Resourceful** - Reputation for integrity\nin team and organisation.
*** Find solutions by imaging what would make\na problem worse, as opposed to better.

right side
** **Alternative** - Prepared to promote\na counter culture.
** **Inspiring** - Generate enthusiasm\nand energy in others.
** **Nurturing** - They enjoy helping both\nindividuals and teams to grow.
** **Empathic** - Sensitive to those around.
** **Disruptive** - Break old status quo\n and help create the new. 
legend
User storeis are placeholder for conversation. 
It is far better to be trusted and respected than to be liked. 
Henry Stimson - The only way to make a man trustworthy is to trust him.
All plans are arguably wrong anyway because, as soon as they are made, the information used to make them is immediately out of date.
The leader is then effective when each team member is able to make the right decision. - Anna Markiewicz friend from US army.
endlegend
@endmindmap