@startmindmap
*[#Orange] The art of leadership
** Meetings
*** Know who knows what, what they want.\nIf you fail - it's called meeting blur.
*** Assume they have something to teach you
*** Act last (then you have most knowledge)
*** Read the room
*** Worst meeting sin: No Agenda
*** Show respect your team by\nasking great questions
*** Have a meeting runner and Historian.
*** Share your notes from the meeting [64]

** Some Practices
*** Mind extroverts and inoverts
*** Blue Tape
*** Remove everything with a screen from your bed
*** Compliments should be short and without dependencies [70]
*** Anti-flow is when you do the hard work
*** Recruitment
**** Have a must list of people you will to work with
**** Week before send a welcoming\nnote (real offer) with some information
**** Discover, Understand, Delight [55]
**** Spent a lot of time\n(50% of your total when you're recruiting)

left side

** Leader
*** When you sign up for things \nyou get them done, always
*** Address gaps with measurable actions
*** Leadership is the job of individuals and can come from everywhere.
*** Be kind (161 - example of leadership)
*** Self-possession
*** Detect Nonsense
*** Grow your team
*** Feedback 
**** Feedback is a gift. 
**** Say the hard thing (sooner is better) [74]
**** Ask for feedback when you give feedback. 
**** When hearing hard thing adopt your\npicked body position helps in self-possession.
**** When hearing hard thing repeat what you've heard.\nFirst impression is often a misunderstanding.

** Manager
*** Let others change your mind.
*** Build trust through successful delegation
*** Delegate more than is comfortable - it's your job to\nbuild great team that handles everything.
*** Performance management is natural \npart of management. Don't emphasize it.
*** Rules need to evolve in unexpected ways\n to account for the arrival of more humans.

** CTO 
*** Don't ask, just act.
*** The stories that define a company remind us\nof what it took for us to get here.\nThey shape the narrative and define the culture.
*** Look for *the stories* and try to distill the meaning.\nThis are the culture, not the words on the wall.

legend
"Meetings are symptom of a disease, not the cure"

"By fostering the belief that the managers are the only leaders, you create hierachy. 
Hierarchy creates silos. Silos often create politcs. This is a disaster."

"Productive team knows itself. The team mebmers know each other's names, and they understand and 
appreciate each other's respective strengths, weaknesses, and motiviations. They are not strangers."

"Feedback is a gift. The phrase is designed to remove the fear of receiving critical feedback, 
to reinforce the fact that you are about to receive a useful thing. I've discovered another interpreation of it,
too. See, the important part of feedback isn't just that you receive the gift; you also need to unwrap it."

endlegend
@endmindmap

